### ISSUE TITLE
Insane error while pruning backups

### ISSUE THREAD

**Issue by kegsmr** [kegsmr/sc4mp-server#56]
```
←[00m [13:17:56] [SC4MP/Main] [INFO] SC4MP Server v0.5.2
←[00m [13:17:56] [SC4MP/Main] (Server) [INFO] Creating subdirectories...
←[00m [13:17:56] [SC4MP/Main] (Server) [INFO] Loading config...
←[00m [13:17:56] [SC4MP/Main] (Server) [INFO] Checking for updates...
←[00m [13:17:56] [SC4MP/Main] (Server) [INFO] Preparing database...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(000-000) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(000-004) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(000-008) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(000-012) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(000-016) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(000-020) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(004-000) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(004-004) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(004-008) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(004-012) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(004-016) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(004-020) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(008-000) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(008-004) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(008-008) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(008-012) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(008-016) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(008-020) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(012-000) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(012-004) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(012-008) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(012-012) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(012-016) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(012-020) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(016-000) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(016-004) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(016-008) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(016-012) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(016-016) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(016-020) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(020-000) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(020-004) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(020-008) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(020-012) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(020-016) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing "_SC4MP\Regions\Hills\(020-020) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(000-000) - (Empty).sc4"...
←[00m [13:17:56] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(000-004) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(000-008) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(000-012) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(000-016) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(000-020) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(004-000) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(004-004) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(004-008) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(004-012) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(004-016) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(004-020) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(008-000) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(008-004) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(008-008) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(008-012) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(008-016) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(008-020) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(012-000) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(012-004) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(012-008) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(012-012) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(012-016) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(012-020) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(016-000) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(016-004) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(016-008) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(016-012) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(016-016) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(016-020) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(020-000) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(020-004) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(020-008) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(020-012) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(020-016) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (DBPF) [INFO] Parsing region view subfile of "_SC4MP\Regions\Hills\(020-020) - (Empty).sc4"...
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] Clearing temporary files...
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] Preparing file tables...
←[00m [13:17:57] [SC4MP/Main] (FileTablesManager) [INFO] Generating file table for "_SC4MP\Plugins"...
←[00m [13:17:57] [SC4MP/Main] (FileTablesManager) [INFO] - done.
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] Preparing regions...
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(004-008) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\4_8\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(004-004) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\4_4\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(004-000) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\4_0\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(008-000) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\8_0\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(008-004) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\8_4\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(008-008) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\8_8\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(008-012) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\8_12\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(008-016) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\8_16\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(008-020) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\8_20\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(012-020) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\12_20\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(000-004) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\0_4\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(012-016) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\12_16\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(012-012) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\12_12\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(012-008) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\12_8\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(012-004) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\12_4\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(012-000) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\12_0\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(016-000) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\16_0\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(016-004) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\16_4\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(016-008) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\16_8\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(016-012) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\16_12\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(016-016) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\16_16\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(000-008) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\0_8\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(016-020) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\16_20\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(020-020) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\20_20\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(020-016) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\20_16\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(020-012) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\20_12\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(020-008) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\20_8\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(020-004) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\20_4\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(020-000) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\20_0\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(000-012) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\0_12\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(000-016) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\0_16\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(000-020) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\0_20\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(004-020) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\4_20\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(004-016) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\4_16\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(004-012) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\4_12\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\(000-000) - (Empty).sc4
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] _SC4MP\Regions\Hills\_Backups\0_0\reset.sc4
←[00m [13:17:57] [SC4MP/Main] (FileTablesManager) [INFO] Generating file table for "_SC4MP\_Temp\outbound\Regions"...
←[00m [13:17:57] [SC4MP/Main] (FileTablesManager) [INFO] - done.
←[00m [13:17:57] [SC4MP/Main] (Server) [INFO] Preparing backups...
←[00m [13:17:57] [SC4MP/Main] (BackupsManager) [INFO] Pruning backups...
←[91m [13:17:57] [SC4MP/Main] (BackupsManager) [ERROR] An error occured while pruning backups.

Traceback (most recent call last):
  File "sc4mpserver.py", line 1450, in backup
  File "sc4mpserver.py", line 1510, in prune
  File "sc4mpserver.py", line 1532, in prune_backup_data
  File "sc4mpserver.py", line 1532, in <listcomp>
  File "pathlib.py", line 1122, in iterdir
FileNotFoundError: [WinError 3] Sistem belirtilen yolu bulamıyor: '_SC4MP\\_Backups\\data'
←[91m [13:17:57] [SC4MP/Main] [FATAL] 'charmap' codec can't encode character '\u0131' in position 440: character maps to <undefined>

Traceback (most recent call last):
  File "sc4mpserver.py", line 1450, in backup
  File "sc4mpserver.py", line 1510, in prune
  File "sc4mpserver.py", line 1532, in prune_backup_data
  File "sc4mpserver.py", line 1532, in <listcomp>
  File "pathlib.py", line 1122, in iterdir
FileNotFoundError: [WinError 3] Sistem belirtilen yolu bulamıyor: '_SC4MP\\_Backups\\data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sc4mpserver.py", line 173, in main
  File "sc4mpserver.py", line 805, in __init__
  File "sc4mpserver.py", line 1341, in prep_backups
  File "sc4mpserver.py", line 1452, in backup
  File "sc4mpserver.py", line 706, in show_error
  File "sc4mpserver.py", line 2752, in write
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u0131' in position 440: character maps to <undefined>
Traceback (most recent call last):
  File "sc4mpserver.py", line 1450, in backup
  File "sc4mpserver.py", line 1510, in prune
  File "sc4mpserver.py", line 1532, in prune_backup_data
  File "sc4mpserver.py", line 1532, in <listcomp>
  File "pathlib.py", line 1122, in iterdir
FileNotFoundError: [WinError 3] Sistem belirtilen yolu bulamıyor: '_SC4MP\\_Backups\\data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sc4mpserver.py", line 173, in main
  File "sc4mpserver.py", line 805, in __init__
  File "sc4mpserver.py", line 1341, in prep_backups
  File "sc4mpserver.py", line 1452, in backup
  File "sc4mpserver.py", line 706, in show_error
  File "sc4mpserver.py", line 2752, in write
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u0131' in position 440: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sc4mpserver.py", line 2764, in <module>
  File "sc4mpserver.py", line 179, in main
  File "sc4mpserver.py", line 724, in fatal_error
  File "sc4mpserver.py", line 2752, in write
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u0131' in position 478: character maps to <undefined>
[4288] Failed to execute script 'sc4mpserver' due to unhandled exception!
```

**Comment by kegsmr** [comment]
Should be fixed.
