### ISSUE TITLE
Server attempts to rename `None` filename savegames and generates errors

### ISSUE THREAD

**Issue by kegsmr** [kegsmr/sc4mp-server#65]
```
[00m [23:56:27] [SC4MP/Main] (Server) [INFO] - renaming "None" to "(052-056) - Edessa - C Colon.sc4"...
[91m [23:56:27] [SC4MP/Main] (Server) [ERROR] join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

Traceback (most recent call last):
  File "sc4mpserver.py", line 1240, in prep_database
  File "ntpath.py", line 117, in join
  File "genericpath.py", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

[00m [23:56:29] [SC4MP/Main] (Server) [INFO] - renaming "None" to "(056-076) - New Armenia - C Colon.sc4"...
[91m [23:56:29] [SC4MP/Main] (Server) [ERROR] join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

Traceback (most recent call last):
  File "sc4mpserver.py", line 1240, in prep_database
  File "ntpath.py", line 117, in join
  File "genericpath.py", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

[00m [23:56:30] [SC4MP/Main] (Server) [INFO] - renaming "None" to "(060-044) - New Hopolin - Homgr.sc4"...
[91m [23:56:30] [SC4MP/Main] (Server) [ERROR] join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

Traceback (most recent call last):
  File "sc4mpserver.py", line 1240, in prep_database
  File "ntpath.py", line 117, in join
  File "genericpath.py", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

[00m [23:56:35] [SC4MP/Main] (Server) [INFO] - renaming "None" to "(088-016) - Bothaven - Prince of Darkness.sc4"...
[91m [23:56:35] [SC4MP/Main] (Server) [ERROR] join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

Traceback (most recent call last):
  File "sc4mpserver.py", line 1240, in prep_database
  File "ntpath.py", line 117, in join
  File "genericpath.py", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

[00m [23:56:35] [SC4MP/Main] (Server) [INFO] - renaming "None" to "(096-008) - TEST - TEST.sc4"...
[91m [23:56:35] [SC4MP/Main] (Server) [ERROR] join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

Traceback (most recent call last):
  File "sc4mpserver.py", line 1240, in prep_database
  File "ntpath.py", line 117, in join
  File "genericpath.py", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

```

**Comment by kegsmr** [comment]
Also encountered error when saving to these tiles

```
[90m [00:01:40] [SC4MP/RgnThread] (RegionsManager) [INFO] Processing task "20241214000140_0d136eb12513d1160529b5fc756c34ae"...
[91m [00:01:40] [SC4MP/RgnThread] (RegionsManager) [ERROR] join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

Traceback (most recent call last):
  File "sc4mpserver.py", line 1775, in run
  File "sc4mpserver.py", line 1719, in run
  File "ntpath.py", line 117, in join
  File "genericpath.py", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```

**Comment by kegsmr** [comment]
Should be fixed now
