### ISSUE TITLE
Error while saving

### ISSUE THREAD

**Issue by kegsmr** [kegsmr/sc4mp-server#66]
Possibly due to the previous file being deleted

```
 [13:44:59] [SC4MP/RgnThread] (RegionsManager) [ERROR] join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

Traceback (most recent call last):
  File "d:/Users/Kegan/Desktop/Projects/mod/sc4/SC4MP/sc4mp-server/sc4mpserver.py", line 1790, in run
    raise e
  File "d:/Users/Kegan/Desktop/Projects/mod/sc4/SC4MP/sc4mp-server/sc4mpserver.py", line 1734, in run
    previous_filename = os.path.join(sc4mp_server_path, "Regions", region, entry["filename"])
  File "C:\Users\Kegan\AppData\Local\Programs\Python\Python38-32\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\Kegan\AppData\Local\Programs\Python\Python38-32\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```

**Comment by kegsmr** [comment]
Should be fixed now
